import { createHash, sign as nodeSign, type KeyObject } from 'node:crypto';
import { computeContentDigest, verifyEd25519 } from '../visa/http-signatures.js';
import type { WebBotAuthKey } from './index.js';

/**
 * Appendix B directory proof-of-possession (draft-ietf-webbotauth-httpsig-protocol-00,
 * formerly draft-meunier-webbotauth-httpsig).
 *
 * The directory server signs its RESPONSE, once per published key, with an HTTP
 * Message Signature made BY that key. A verifier that checks the proof learns
 * the directory actually holds the private half of each key it publishes, not
 * just that it can serve a JSON blob over TLS.
 *
 * The covered set is fixed by the draft: `@authority;req` (the authority of the
 * request that fetched the directory, so the proof is bound to the host that
 * served it) and `content-digest` (over the response body, so the key list
 * cannot be swapped under a captured signature). Parameters carry
 * created/expires, keyid = the key's RFC 7638 thumbprint, and
 * tag="http-message-signatures-directory".
 *
 * The WG has since published a normative example, generated by this module:
 * -02 Appendix E.2.3 "Signed directory response" is our contributed test vector
 * (issue #120), so the base construction below is no longer an interpretation.
 * scripts/verify-directory-proof-vectors.mjs --from-draft re-checks it against
 * the rendered draft.
 *
 * Two -02 points for when we start SERVING proofs (we do not yet):
 *   - §B.1 makes the proof OPTIONAL for keys a verifier resolved itself and
 *     RECOMMENDED generally; it is REQUIRED only to attribute REDISTRIBUTED key
 *     material to a URL (§5.5.3). That is why the verifier's grace flag
 *     defaults to tolerating an absent proof.
 *   - §C.8: do not set a short `expires`. Where the key set is redistributed,
 *     revocation latency is already floored by republication, so a short expiry
 *     buys nothing and drops every consumer to unverified at once. Set it well
 *     beyond any republication interval; the vector's far-future constant is
 *     deliberate.
 */

export const DIRECTORY_PROOF_TAG = 'http-message-signatures-directory';

/**
 * Per-key proof outcome. `absent` = the directory offered no proof for this key
 * (tolerated under grace, dropped without it). `invalid` = a proof was offered
 * and failed verification (a bad window, a wrong key, or a broken signature);
 * never tolerated. `valid` = a proof was offered and verified.
 */
export type KeyProofStatus = 'valid' | 'invalid' | 'absent';

/** Build the RFC 9421 signature base for one directory proof signature. */
export function buildDirectoryProofBase(params: {
  authority: string;
  contentDigest: string;
  created: number;
  expires: number;
  keyid: string;
}): string {
  const sigParams =
    `("@authority";req "content-digest")` +
    `;created=${params.created};expires=${params.expires}` +
    `;keyid="${params.keyid}";tag="${DIRECTORY_PROOF_TAG}"`;
  return [
    `"@authority";req: ${params.authority}`,
    `"content-digest": ${params.contentDigest}`,
    `"@signature-params": ${sigParams}`,
  ].join('\n');
}

export interface DirectoryProofSigner {
  privateKey: KeyObject;
  /** The key's RFC 7638 thumbprint, used as the signature keyid. */
  keyid: string;
}

/**
 * Produce Appendix B response headers for a directory body. Test/tooling side:
 * signs one proof per signer, all bound to `authority` and the body digest.
 */
export function signDirectoryResponse(params: {
  signers: DirectoryProofSigner[];
  authority: string;
  body: string;
  created: number;
  expires: number;
}): { 'content-digest': string; 'signature-input': string; signature: string } {
  const contentDigest = computeContentDigest(params.body);
  const inputs: string[] = [];
  const sigs: string[] = [];
  params.signers.forEach((signer, i) => {
    const label = `binding${i}`;
    const base = buildDirectoryProofBase({
      authority: params.authority,
      contentDigest,
      created: params.created,
      expires: params.expires,
      keyid: signer.keyid,
    });
    const sig = nodeSign(null, Buffer.from(base), signer.privateKey);
    const sigParams =
      `("@authority";req "content-digest")` +
      `;created=${params.created};expires=${params.expires}` +
      `;keyid="${signer.keyid}";tag="${DIRECTORY_PROOF_TAG}"`;
    inputs.push(`${label}=${sigParams}`);
    sigs.push(`${label}=:${sig.toString('base64')}:`);
  });
  return {
    'content-digest': contentDigest,
    'signature-input': inputs.join(', '),
    signature: sigs.join(', '),
  };
}

/**
 * The only covered component list Appendix B allows, as its serialized Inner
 * List. A proof covering anything else, or the same two in another order, is
 * one we cannot build the base for, so it is `invalid` rather than `absent`.
 */
const PROOF_COVERED_LIST = '("@authority";req "content-digest")';

/** The digest algorithms we can check a response Content-Digest against. */
const DIGEST_ALGORITHMS = { 'sha-256': 'sha256', 'sha-512': 'sha512' } as const;

/** A Structured Field bare item, as far as the proof parameters need one. */
type BareItem =
  | { kind: 'string'; value: string }
  | { kind: 'integer'; value: number }
  | { kind: 'other' };

/**
 * Split a Structured Field Dictionary into its members, each value kept
 * verbatim (parameters included) so it can feed a signature base byte for
 * byte. Quoted strings are respected, so a comma or `;` inside a String Item
 * cannot split a member. A repeated key keeps its first position and takes the
 * later value (RFC 8941 Section 4.2.2). Returns undefined when the field does
 * not read as a dictionary.
 */
function dictionaryMembers(headerValue: string): Map<string, string> | undefined {
  const out = new Map<string, string>();
  let i = 0;
  const n = headerValue.length;
  while (i < n) {
    while (i < n && /[\s,]/.test(headerValue[i] as string)) i++;
    if (i >= n) break;
    const keyStart = i;
    while (i < n && /[A-Za-z0-9_.*-]/.test(headerValue[i] as string)) i++;
    const key = headerValue.slice(keyStart, i);
    if (key === '' || headerValue[i] !== '=') return undefined;
    i++;
    const valueStart = i;
    let inQuotes = false;
    while (i < n) {
      const ch = headerValue[i] as string;
      if (inQuotes) {
        if (ch === '\\') { i += 2; continue; }
        if (ch === '"') inQuotes = false;
      } else if (ch === '"') {
        inQuotes = true;
      } else if (ch === ',') {
        break;
      }
      i++;
    }
    if (inQuotes) return undefined;
    out.set(key, headerValue.slice(valueStart, i).trim());
  }
  return out;
}

/**
 * Parse Structured Field parameters (`;key=value;key2`) into a map. Returns
 * undefined on anything that is not well formed, so a value we misread can
 * never select a key or a window.
 */
function parseParameters(text: string): Map<string, BareItem> | undefined {
  const out = new Map<string, BareItem>();
  let rest = text;
  while (rest.length > 0) {
    const m = rest.match(/^;\s*([a-z*][a-z0-9_.*-]*)/);
    if (!m) return undefined;
    const name = m[1] as string;
    rest = rest.slice(m[0].length);
    if (!rest.startsWith('=')) {
      out.set(name, { kind: 'other' }); // Boolean true
      continue;
    }
    rest = rest.slice(1);
    const str = rest.match(/^"((?:[^"\\]|\\["\\])*)"/);
    if (str) {
      out.set(name, { kind: 'string', value: (str[1] as string).replace(/\\(["\\])/g, '$1') });
      rest = rest.slice(str[0].length);
      continue;
    }
    const int = rest.match(/^-?[0-9]{1,15}(?![0-9.])/);
    if (int) {
      out.set(name, { kind: 'integer', value: Number(int[0]) });
      rest = rest.slice(int[0].length);
      continue;
    }
    const other = rest.match(
      /^(?:-?[0-9]{1,12}\.[0-9]{1,3}|[A-Za-z*][A-Za-z0-9!#$%&'*+.^_`|~:/-]*|:[A-Za-z0-9+/=]*:|\?[01])/,
    );
    if (!other) return undefined;
    out.set(name, { kind: 'other' });
    rest = rest.slice(other[0].length);
  }
  return out;
}

interface ProofMember {
  /** The member value exactly as received: the `@signature-params` line. */
  raw: string;
  /** True only when the covered list is exactly PROOF_COVERED_LIST. */
  coveredExact: boolean;
  params: Map<string, BareItem>;
}

/** Read one Signature-Input member value into its covered list and parameters. */
function parseProofMember(raw: string): ProofMember | undefined {
  if (!raw.startsWith('(')) return undefined;
  let i = 1;
  let inQuotes = false;
  for (; i < raw.length; i++) {
    const ch = raw[i] as string;
    if (inQuotes) {
      if (ch === '\\') { i++; continue; }
      if (ch === '"') inQuotes = false;
    } else if (ch === '"') {
      inQuotes = true;
    } else if (ch === ')') {
      break;
    }
  }
  if (i >= raw.length) return undefined;
  const list = raw.slice(0, i + 1);
  const params = parseParameters(raw.slice(i + 1));
  if (!params) return undefined;
  return { raw, coveredExact: list === PROOF_COVERED_LIST, params };
}

const stringParam = (params: Map<string, BareItem>, name: string): string | undefined => {
  const item = params.get(name);
  return item?.kind === 'string' ? item.value : undefined;
};

/**
 * True when the response Content-Digest header matches the body. Every
 * algorithm we know (sha-256, sha-512) that the header carries must match, and
 * it must carry at least one; algorithms we do not know are ignored, per RFC
 * 9530. A missing or unreadable header is a mismatch.
 */
function contentDigestMatchesBody(header: string | undefined, body: string): boolean {
  if (header === undefined) return false;
  const members = dictionaryMembers(header);
  if (!members) return false;
  let checked = 0;
  for (const [name, algorithm] of Object.entries(DIGEST_ALGORITHMS)) {
    const value = members.get(name);
    if (value === undefined) continue;
    const bytes = value.match(/^:([A-Za-z0-9+/]*={0,2}):$/);
    if (!bytes) return false;
    const expected = createHash(algorithm).update(body).digest();
    if (!Buffer.from(bytes[1] as string, 'base64').equals(expected)) return false;
    checked++;
  }
  return checked > 0;
}

/**
 * Classify every key in `keys` by its Appendix B proof. A key with no matching
 * proof signature is `absent`; a key whose proof is present but fails is
 * `invalid`; a key whose proof verifies is `valid`. Proof signatures for keyids
 * not in the directory are ignored.
 *
 * A proof fails when its covered list is not exactly
 * `("@authority";req "content-digest")`, its `alg` is present and not
 * `ed25519`, its window is bad, its signature bytes are missing, the response
 * Content-Digest is absent or does not match the body, or the signature does
 * not verify.
 *
 * The signature base is rebuilt from the bytes the directory sent, not from a
 * template: `@signature-params` is the Signature-Input member value verbatim
 * (RFC 9421 Section 2.3), so parameter order and any parameter we do not read
 * (`alg`, `nonce`, unknown ones) are preserved, and the `content-digest` line
 * is the response header as received. Until 2026-09-25 this path rebuilt both
 * from a template, which dropped chatgpt.com's `alg="ed25519"` and classified
 * its every key invalid.
 */
export function verifyDirectoryProofs(params: {
  authority: string;
  body: string;
  /**
   * The response Content-Digest header as received. Covered verbatim by the
   * proof and checked against `body`. Absent with a proof present = `invalid`.
   */
  contentDigest?: string | undefined;
  signatureInput: string | undefined;
  signature: string | undefined;
  now: number;
  skewSeconds: number;
  keys: WebBotAuthKey[];
}): Map<string, KeyProofStatus> {
  const status = new Map<string, KeyProofStatus>();
  for (const key of params.keys) status.set(key.thumbprint, 'absent');

  if (!params.signatureInput || !params.signature) return status;

  const inputs = dictionaryMembers(params.signatureInput);
  const signatures = dictionaryMembers(params.signature);
  if (!inputs) return status;
  const keyByThumbprint = new Map(params.keys.map((key) => [key.thumbprint, key]));
  const contentDigest = params.contentDigest?.trim();
  let digestOk: boolean | undefined;

  for (const [label, raw] of inputs) {
    const proof = parseProofMember(raw);
    if (!proof) continue; // unreadable: cannot attribute it to a key
    if (stringParam(proof.params, 'tag') !== DIRECTORY_PROOF_TAG) continue; // not a directory proof
    const keyid = stringParam(proof.params, 'keyid');
    if (keyid === undefined) continue;
    const key = keyByThumbprint.get(keyid);
    if (!key) continue; // a proof for a key not in this directory: ignore it

    // From here the proof is "offered" for a known key: any failure is invalid,
    // never absent, so it can never be tolerated under grace.
    const invalid = (): void => {
      status.set(key.thumbprint, 'invalid');
    };
    if (!proof.coveredExact) { invalid(); continue; }

    const created = proof.params.get('created');
    const expires = proof.params.get('expires');
    if (created?.kind !== 'integer' || expires?.kind !== 'integer') { invalid(); continue; }
    if (
      created.value > params.now + params.skewSeconds ||
      expires.value + params.skewSeconds < params.now
    ) {
      invalid();
      continue;
    }
    // The key is Ed25519, so an explicit alg must say so. Absent is accepted
    // (the E.2.3 vector carries none).
    if (proof.params.has('alg') && stringParam(proof.params, 'alg') !== 'ed25519') {
      invalid();
      continue;
    }

    const sigValue = signatures?.get(label)?.match(/^:([A-Za-z0-9+/]*={0,2}):$/);
    if (!sigValue) { invalid(); continue; }
    const sig = Buffer.from(sigValue[1] as string, 'base64');

    digestOk ??= contentDigestMatchesBody(contentDigest, params.body);
    if (!digestOk || contentDigest === undefined) { invalid(); continue; }

    const base = [
      `"@authority";req: ${params.authority}`,
      `"content-digest": ${contentDigest}`,
      `"@signature-params": ${proof.raw}`,
    ].join('\n');
    let ok = false;
    try {
      ok = verifyEd25519({ kty: 'OKP', crv: 'Ed25519', x: key.x }, base, sig);
    } catch {
      ok = false;
    }
    status.set(key.thumbprint, ok ? 'valid' : 'invalid');
  }

  return status;
}
