<?php
/**
 * TS↔PHP parity, enforced mechanically: replays every case in
 * tests/fixtures/policy-golden.json — generated by running the REAL
 * Shopify-app decision logic (applyMerchantPolicy, parseAgentPolicy,
 * resolveRule) over a broad matrix — through the PHP ports and asserts
 * byte-identical decisions.
 *
 * If this test fails after a legitimate TS change, regenerate the golden
 * file (scripts/generate-policy-golden.ts) and port the change; never adjust
 * the PHP side alone.
 *
 * @package AVA_Pay
 */

use PHPUnit\Framework\TestCase;

final class PolicyGoldenTest extends TestCase {

	/** @var array */
	private static $golden;

	public static function setUpBeforeClass(): void {
		self::$golden = ava_pay_load_fixture( 'policy-golden.json' );
	}

	public function test_decision_parity(): void {
		$cases = self::$golden['decisionCases'];
		$this->assertGreaterThan( 500, count( $cases ), 'golden file looks truncated' );

		foreach ( $cases as $case ) {
			$policy = null;
			if ( null !== $case['settings']['policyJson'] ) {
				$parsed = AVA_Pay_Agent_Policy::parse( $case['settings']['policyJson'] );
				$this->assertTrue( $parsed['ok'], "{$case['name']}: golden policy must parse" );
				$policy = $parsed['policy'];
			}
			$settings = array(
				'acceptVerifiedAgents'    => $case['settings']['acceptVerifiedAgents'],
				'defaultDiscountPct'      => $case['settings']['defaultDiscountPct'],
				'maxDiscountPct'          => $case['settings']['maxDiscountPct'],
				'identityOnlyDiscountPct' => $case['settings']['identityOnlyDiscountPct'],
				'policy'                  => $policy,
			);

			$actual = AVA_Pay_Policy::apply_merchant_policy( $settings, $case['result'], $case['platform'] );

			$this->assertSame(
				self::normalize( $case['expected'] ),
				self::normalize( $actual ),
				"decision mismatch: {$case['name']}"
			);
		}
	}

	public function test_validation_parity(): void {
		foreach ( self::$golden['validationCases'] as $case ) {
			$actual = AVA_Pay_Agent_Policy::parse( $case['json'] );
			$this->assertSame(
				self::normalize( $case['expected'] ),
				self::normalize( $actual ),
				"validation mismatch: {$case['name']}"
			);
		}
	}

	public function test_resolve_rule_parity(): void {
		foreach ( self::$golden['resolveCases'] as $case ) {
			$parsed = AVA_Pay_Agent_Policy::parse( $case['policyJson'] );
			$this->assertTrue( $parsed['ok'] );
			$actual = AVA_Pay_Agent_Policy::resolve_rule( $parsed['policy'], $case['platform'] );
			$this->assertSame(
				self::normalize( $case['expected'] ),
				self::normalize( $actual ),
				"resolve mismatch: {$case['name']}"
			);
		}
	}

	/**
	 * Sort keys recursively so assertSame compares structure + values + types,
	 * not key insertion order.
	 *
	 * @param mixed $value Any JSON-shaped value.
	 * @return mixed
	 */
	private static function normalize( $value ) {
		if ( ! is_array( $value ) ) {
			return $value;
		}
		$out = array();
		foreach ( $value as $k => $v ) {
			$out[ $k ] = self::normalize( $v );
		}
		if ( array_keys( $out ) !== range( 0, count( $out ) - 1 ) ) {
			ksort( $out );
		}
		return $out;
	}
}
